//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUdWithDatabaseandJquery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expire
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
    }
}
