//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUdWithDatabaseandJquery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgcStoreEntities : DbContext
    {
        public AgcStoreEntities()
            : base("name=AgcStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adds> Adds { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<expire> expire { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<vistor> vistor { get; set; }
    }
}
